name: Selectively pull apps from truenas/apps and run modifications

on:
  #schedule:
  #  - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_and_patch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Checkout truenas/apps
      uses: actions/checkout@v4
      with:
        repository: truenas/apps
        ref: master
        path: truenas-apps
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          library/*
          migration_helpers/*
          catalog.json
          cspell.config.yaml
          features_capability.json
          trains/stable/ix-app/*
          trains/community/linkding/*
          trains/community/immich/*
          trains/stable/diskoverdata/*
          trains/stable/home-assistant/*

    - name: Patch catalog.json
      run: |
        set -x
        ROOT=$(pwd)
        pip install pyyaml
        python "$ROOT/.github/strip_catalog.py" "$ROOT/truenas-apps"

    - name: Cleanup
      run: |
        set -x
        ROOT=$(pwd)
        mv "${ROOT}/truenas-apps/"* "${ROOT}/"
        rm -rf "${ROOT}/truenas-apps"

    - name: Commit changes if there are any
      run: |
        set -x
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -am "Workflow: update"
        git push
